# Generated by Django 5.1 on 2024-08-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=255)),
            ],
        ),
    ]
