# Generated by Django 5.1 on 2024-08-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
