# Generated by Django 5.1 on 2024-08-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corte', '0004_alter_agendamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='modelo_corte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.CharField(max_length=50),
        ),
    ]
